### ISSUE TITLE
live reload

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#106]
Setup a live reload mechanism for development (i.e. browsersync)

**Comment by mef** [comment]
For the record, config used in local dev environment (in _config.yml):

````yaml
# Browsersync config
browsersync:
  logLevel: warn
  logFileChanges: false
  reloadDelay: 750
````
