### ISSUE TITLE
migrate conversion optimization landing page

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#39]
The content from conversion optimization landing page should be migrated to Hexo.

Source: content is to be taken from the [current page](/Mango-information-systems/mango-is-website/blob/master/corporate-business-intelligence/index.html) in branch `master`.

Target: [page](https://github.com/Mango-information-systems/mango-is-website/tree/hexo-wip/source/convert/index.md) in branch `hexo-wip`.

New logic: landing page content is now defined exclusively inside the yaml front matter. An array called `sections` hosts the content, which is used by the theme's [`landing.ejs`](https://github.com/Mango-information-systems/mango-is-website/blob/hexo-wip/themes/mango-information-systems/layout/landing.ejs) template.

````yaml
sections:
 - 
  # top section: value proposition
  background-image: /img/bg/eagle.jpg
  content:
   - type: h1
     class: small
     value: Higher BI adoption
   - type: h1
     class: small
     value: More successful projects
   - type: h1
     class: small
     value: Lower Data&dash;Warehousing costs
   - type: p
     value: <small><em>Let us help you succeed</em></small>
   - type: cta
     value: View offers
     primary: true
     trg: /view-packages
     href: "#packages"
````

background images: not defined yet, temporary images can be used as placeholders (or no image at all).

:information_source: The landing page [Business Intelligence](https://github.com/Mango-information-systems/mango-is-website/tree/hexo-wip/source/corporate-business-intelligence/index.md) has a similar structure and can be used as a model.

**Comment by mef** [comment]
@blueclock I'll use `<td class="price">` for price cells in the pricing tables.

Syntax at landing page side: 

````
   - type: pricing
     offers:
      - 
       title: Analysis
       content: 
        - Requirements analysis
        - Data modeling
        - Acceptance and testing
        - Design of reports/dashboards
       price: starts at 1600€
       CTA: 
        label: Get a quote
        trg: /package-bi-analysis
      - 
       title: Development
       content: 
````
